### PR TITLE
fix: update user_id and party_id being attributes and not methods

### PR DESCRIPTION
**Pull request by Jmgr**
This PR updates user_id and party_id being attributes and not methods (updated in https://github.com/NillionNetwork/nillion/pull/1430)

### CODE REVIEW

**Comment by oceans404** [comment]
this change should not be merged in until after https://github.com/NillionNetwork/nillion/pull/1430 ^

**Comment by manel1874** [comment]
We also have to change all examples inside the `voting_tutorial` folder.

**Review by manel1874 — CHANGES_REQUESTED** [review]
1. We also have to change all examples inside the `voting_tutorial` folder. 
2. I suggest making a note in the README file saying the examples only work for `>0.1.1`  release version (or whatever version). 
3. Is there a way to tell a user they have a deprecated version when they try to run an example with the new api (probably this is not worth doing)?
4. Other than that, looks fine whenever we have a new release.

**Comment by Jmgr** [comment]
> 1. We also have to change all examples inside the `voting_tutorial` folder.

Yes, and also update any example we add until the release. Maybe we could create a `0.1.2` branch where we could merge other API changing PRs?

> 
>     2. I suggest making a note in the README file saying the examples only work for `>0.1.1`  release version (or whatever version).

Sure.

> 
>     3. Is there a way to tell a user they have a deprecated version when they try to run an example with the new api (probably this is not worth doing)?

Not as far as I know.

**Review by oceans404 — APPROVED** [review]

**Pull request merged**
